# Generated by Django 2.1 on 2021-03-04 20:12

import bot_manager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('symbol', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('family', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('interval', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('stock_type', models.CharField(choices=[('1', 'Stock'), ('2', 'Forex'), ('3', 'Crypto')], default='1', max_length=1)),
                ('enable', models.BooleanField(default=False)),
                ('csv_file', models.FileField(blank=True, default='', null=True, upload_to='documents')),
                ('send_sms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('entry_rule', models.TextField(default='', validators=[bot_manager.models.validate_json])),
                ('exit_rule', models.TextField(default='', validators=[bot_manager.models.validate_json])),
                ('value', models.IntegerField(default=0)),
                ('backtest', models.BooleanField(default=False)),
                ('time_from', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_entry_rule', models.DateTimeField(blank=True, null=True)),
                ('datetime_entry', models.DateTimeField(blank=True, null=True)),
                ('datetime_exist', models.DateTimeField(blank=True, null=True)),
                ('datetime_exit_rule', models.DateTimeField(blank=True, null=True)),
                ('price_open', models.FloatField(blank=True, null=True)),
                ('price_close', models.FloatField(blank=True, null=True)),
                ('bot_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_manager.BotSetting')),
            ],
        ),
        migrations.AddField(
            model_name='botsetting',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot_manager.Strategy'),
        ),
    ]
