db:
  image: postgres:alpine
  env_file: config/env.secret
  volumes:
    - .:/usr/src/app
  ports:
    - "127.0.0.1:5432:5432"
  logging:
    options:
      max-size: "10m"
      max-file: "3"

nginx:
  restart: always
  build: ./config/nginx/
  ports:
    - "80:80"
  volumes:
    - ./log/nginx:/var/log/nginx
  volumes_from:
    - web
  links:
    - web:web
  logging:
    options:
      max-size: "10m"
      max-file: "3"

redis:
  restart: always
  image: redis:4.0
  ports:
    - "6379:6379"
  logging:
    options:
      max-size: "10m"
      max-file: "3"

web:
  restart: always
  build: .
  dockerfile: Dockerfile
  expose:
    - "8000"
  env_file: config/env.secret
  volumes:
    - .:/usr/src/app
  links:
    - redis:redis
    - celery:celery
    - db:db
  command: ./config/uwsgi/init.sh
  logging:
    options:
      max-size: "10m"
      max-file: "3"

celery:
#  restart: always
  build: .
  dockerfile: Dockerfile
  environment:
    - C_FORCE_ROOT=1
  command: celery -A app.celery worker -B --loglevel=info --concurrency=4
  volumes:
    - .:/usr/src/app
  env_file: config/env.secret
  links:
    - redis:redis
    - db:db
  logging:
    options:
      max-size: "10m"
      max-file: "3"