# Generated by Django 2.1 on 2020-01-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.URLField(default='', max_length=300)),
                ('file_name', models.CharField(default='not_available', max_length=200)),
                ('path', models.CharField(default='not_available', max_length=200)),
                ('type', models.CharField(choices=[('image', 'image'), ('text', 'text')], default='text', max_length=10)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=300)),
                ('status', models.CharField(choices=[('new', 'new'), ('inprogress', 'inprogress'), ('succeed', 'succeed'), ('abandoned', 'abandoned')], default='new', max_length=10)),
                ('counter', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('image', 'image'), ('text', 'text')], default='text', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Task'),
        ),
    ]
