# Generated by Django 2.1 on 2020-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('symbol', models.CharField(default='', max_length=20)),
                ('family', models.CharField(default='', max_length=20)),
                ('token', models.CharField(default='', max_length=50)),
                ('volume_percenage', models.IntegerField(default=0)),
                ('price_percenage', models.IntegerField(default=0)),
                ('time_resolution', models.IntegerField(default=1)),
                ('enable', models.BooleanField()),
            ],
        ),
    ]
