# Generated by Django 2.1 on 2020-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerDetect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('volume', models.CharField(default='', max_length=20)),
                ('max_volume', models.CharField(default='', max_length=20)),
                ('price_open', models.CharField(default='', max_length=20)),
                ('price_close', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
