# Generated by Django 2.1 on 2020-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_beerdetect'),
    ]

    operations = [
        migrations.CreateModel(
            name='BearDetect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('volume', models.FloatField()),
                ('max_volume', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_close', models.FloatField()),
                ('price_percenage', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BeerDetect',
        ),
        migrations.AddField(
            model_name='actionsettings',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionsettings',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionsettings',
            name='time_resolution',
            field=models.CharField(choices=[('1', '1 Minutes'), ('5', '5 Minutes'), ('15', '15 Minutes'), ('30', '30 Minutes'), ('60', '60 Minutes'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], default=1, max_length=2),
        ),
    ]
