# Generated by Django 2.1 on 2020-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_auto_20200911_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='beardetect',
            name='time_resolution',
            field=models.CharField(choices=[('1', '1 Minutes'), ('5', '5 Minutes'), ('15', '15 Minutes'), ('30', '30 Minutes'), ('60', '60 Minutes'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], default=1, max_length=2),
        ),
    ]
