# Generated by Django 2.1 on 2020-09-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_actionsettings_bull_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsettings',
            name='stock_type',
            field=models.CharField(choices=[('1', 'Stock'), ('2', 'Forex'), ('3', 'Crypto')], default='1', max_length=1),
        ),
    ]
