# Generated by Django 2.1 on 2020-09-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_actionsettings_stock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsettings',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
