# Generated by Django 2.1 on 2020-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_auto_20200918_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsettings',
            name='csv_file',
            field=models.FileField(default='', upload_to='documents'),
        ),
    ]
