# Generated by Django 2.1 on 2020-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_actionsettings_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsettings',
            name='csv_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents'),
        ),
    ]
