# Generated by Django 2.1 on 2020-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0011_auto_20200918_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsettings',
            name='family',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actionsettings',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actionsettings',
            name='token',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
