# Generated by Django 2.1 on 2020-09-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0012_auto_20200918_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsettings',
            name='forced',
            field=models.BooleanField(default=False),
        ),
    ]
