# Generated by Django 2.1 on 2020-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0013_actionsettings_forced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beardetect',
            name='symbol',
            field=models.CharField(default='', max_length=50),
        ),
    ]
