# Generated by Django 2.1 on 2020-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0014_auto_20200922_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='beardetect',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
