# Generated by Django 2.1 on 2020-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0015_beardetect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsettings',
            name='time_resolution',
            field=models.CharField(choices=[('1', '1 Minutes'), ('5', '5 Minutes'), ('15', '15 Minutes')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='beardetect',
            name='time_resolution',
            field=models.CharField(choices=[('1', '1 Minutes'), ('5', '5 Minutes'), ('15', '15 Minutes')], default=1, max_length=2),
        ),
    ]
