# Generated by Django 2.1 on 2020-09-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0016_auto_20200923_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='beardetect',
            name='action_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='detector.ActionSettings'),
        ),
    ]
