# Generated by Django 2.1 on 2020-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0018_beardetect_volume_percenage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beardetect',
            name='price_percenage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='beardetect',
            name='volume_percenage',
            field=models.FloatField(default=0),
        ),
    ]
