# Generated by Django 2.1 on 2020-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0019_auto_20201002_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsettings',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
